#!/bin/bash
set -ex

export DEBIAN_FRONTEND=noninteractive

sed -i 's/# deb-src/deb-src/g' /etc/apt/sources.list
apt-get update
apt-get dist-upgrade -y

apt-get install -y --no-install-recommends \
    bison \
    flex \
    g++ \
    git \
    libgdk-pixbuf-2.0-dev \
    libgl-dev \
    libgtk-4-dev \
    libpciaccess-dev \
    libpython3.10-dev \
    libsodium-dev \
    libssl-dev \
    libx11-xcb-dev \
    nasm \
    pkg-config \
    python3-pip \
    wget

pip3 install meson ninja tomli
apt-get clean
rm -rf /var/lib/apt/lists/*
