#!/bin/bash
set -ex

apt-get update
apt-get dist-upgrade -y

apt-get install -y --no-install-recommends \
    gir1.2-glib-2.0 \
    libgirepository-1.0-1 \
    libgl1 \
    libpciaccess0 \
    libpython3.10 \
    libssl3 \
    libwayland-cursor0 \
    libx11-xcb1 \
    python3 \
    python3-pip

apt-get clean && \
rm -rf /var/lib/apt/lists/*
