#!/bin/bash
set -ex

export DEBIAN_FRONTEND=noninteractive

sed -i 's/# deb-src/deb-src/g' /etc/apt/sources.list
apt-get update
apt-get dist-upgrade -y

apt-get install -y --no-install-recommends \
    git \
    g++ \
    pkg-config \
    libssl-dev \
    flex \
    bison \
    python3-pip \

pip3 install meson ninja
apt-get clean
rm -rf /var/lib/apt/lists/*
