#!/bin/bash
set -ex

apt-get update
apt-get dist-upgrade -y

apt-get install -y --no-install-recommends \
    gir1.2-gtk-4.0 \
    libegl1 \
    libgdk-pixbuf-2.0-0 \
    libgl1 \
    libgtk-4-1 \
    libpciaccess0 \
    libpython3.10 \
    libssl3 \
    libwayland-cursor0 \
    libx11-xcb1 \
    python3 \
    python3-pip

apt-get clean && \
rm -rf /var/lib/apt/lists/*
