name: Build and publish docker image
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set envs
      run: |
        echo "VERSION=$(echo '${{ github.ref_name }}' | sed -e 's/^v//')" >> $GITHUB_ENV
        echo "UBUNTU_VERSION=$(echo $VERSION | cut -f1 -d-)" >> $GITHUB_ENV
        echo "GSTREAMER_CHECKOUT=$(echo $VERSION | cut -f2 -d-)" >> $GITHUB_ENV

    - name: Build images
      run: |
        BUILD_DEV=1 ./build-release.sh
        BUILD_DEV_WITH_SOURCE=1 ./build-release.sh
        BUILD_PROD=1 ./build-release.sh
        BUILD_PROD_DBG=1 ./build-release.sh

    - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push images
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/gstreamer
        
        docker tag streamstorage/gstreamer:$VERSION-dev $IMAGE_ID:$VERSION-dev
        docker push $IMAGE_ID:$VERSION-dev
        docker tag streamstorage/gstreamer:$VERSION-dev-with-source $IMAGE_ID:$VERSION-dev-with-source
        docker push $IMAGE_ID:$VERSION-dev-with-source
        docker tag streamstorage/gstreamer:$VERSION-prod $IMAGE_ID:$VERSION-prod
        docker push $IMAGE_ID:$VERSION-prod
        docker tag streamstorage/gstreamer:$VERSION-prod-dbg $IMAGE_ID:$VERSION-prod-dbg
        docker push $IMAGE_ID:$VERSION-prod-dbg
